### ISSUE TITLE
Discovered MQTT entities with a name that is equal to the device name

### ISSUE THREAD

**Issue by NeilCrosby** [mikakoivisto/controlmyspa-ha-mqtt#12]
Hi there - thanks for building this addon - it's really helpful. As of the Home Assistant 2023.8 release though, a warning has begun to display in home assistant, per the breaking changes in https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes

<img width="582" alt="Screenshot 2023-08-13 at 13 43 37" src="https://github.com/mikakoivisto/controlmyspa-ha-mqtt/assets/31119/def39caa-af23-4950-8f7c-115fbc38739d">

So, as requested by the warning, I'm providing a heads up to you so that this can get fixed before it becomes a proper problem in a later release.

**Comment by mikakoivisto** [comment]
﻿﻿Thanks. I’ll look into it and get it fixed before that.On 13. Aug 2023, at 15.51, Neil Crosby ***@***.***> wrote:﻿
Hi there - thanks for building this addon - it's really helpful. As of the Home Assistant 2023.8 release though, a warning has begun to display in home assistant, per the breaking changes in https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes

So, as requested by the warning, I'm providing a heads up to you so that this can get fixed before it becomes a proper problem in a later release.

**Comment by mikakoivisto** [comment]
Looks like it's working fine in 2024.4
